### ISSUE TITLE
Delete a single entity

### ISSUE THREAD

**Issue by crossbap** [BapCat/Remodel#25]
Currently, Repo::delete() just deletes everything in the table - not very useful - this needs to accept an Entity, or we need another method that does.

I would also rename that method to deleteAll(), unless the original intent was to provide delete support for a single entity.

**Comment by LordMonoxide** [comment]
This is incorrect; calling delete deletes whatever your where clause restricts it to.  If you haven't specified a where clause, it will delete everything.  This is intended and expected behaviour.

```
$repo->withId($id)->delete();
```
